" vundle
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-repeat'
Plugin 'uxcn/vim-x2x'

filetype plugin indent on

" vim
set nocompatible
set encoding=utf-8

set wildmenu
set autoread

set scrolloff=1
set sidescrolloff=5

set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+

set smarttab
set smartindent
set showcmd

set shiftround
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

set incsearch

set number
set relativenumber
syntax on

" ultisnips
let g:UltiSnipsExpandTrigger="<c-y>"
let g:UltiSnipsJumpForwardTrigger="<c-i>"
let g:UltiSnipsJumpBackwardTrigger="<c-o>"

" clang-format
noremap  <leader>f           :pyf ~/.vim/python/clang-format.py<cr>
inoremap <leader>f      <c-o>:pyf ~/.vim/python/clang-format.py<cr>
nnoremap <leader>ff          :%pyf ~/.vim/python/clang-format.py<cr>

" x2x
xmap <leader>b  <plug>x2b
nmap <leader>b  <plug>x2b
xmap <leader>o  <plug>x2o
nmap <leader>o  <plug>x2o
xmap <leader>d  <plug>x2d
nmap <leader>d  <plug>x2d
xmap <leader>h  <plug>x2h
nmap <leader>h  <plug>x2h
