#!/bin/sh

# %File% - ?

# %License%

# author: %user%

USAGE="%File% <cmd> [arg...]\\n

cmds                        \\n
                            \\n
cmd\\t- ?"

if (( $# <= 0 )); then

    echo -e ${USAGE}
    exit 1

fi

CMD=$1

shift 1

    
if [[ ${CMD} == "help" ]]; then

    echo -e ${USAGE}
    exit 0

fi

if /usr/bin/which %File%-${CMD} &>>/dev/null; then

    exec %File%-${CMD} "$@"

fi

/bin/echo -e "unknown command: ${CMD}\\n"
/bin/echo -e ${USAGE}
exit 1
